rawData:
  columns:
    - count
    - hate_speech
    - offensive_language
    - neither
    - class
    - tweet

  dataTypes:
    count: int64
    hate_speech: int64
    offensive_language: int64
    neither: int64
    class: int64
    tweet: str

imbalanceData:
  columns:
    - id
    - label
    - tweet

  dataTypes:
    id: int64
    label: int64
    tweet: str
